// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yylgysaoxzwgzwudphcc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5bGd5c2FveHp3Z3p3dWRwaGNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNjgwMTIsImV4cCI6MjA3MDg0NDAxMn0.5d5cdr3e7Biheoc4dRvvP71c_G9BFt-pT2OHwpdCUbM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});